name=input("Enter your name :-")
sem=(input("Enter your semister :-"))
city=input("Enter your city :-")
pincode=int(input("Enter your pincode :-"))
print('\n\n\n')
print("Student name is :-",name)
print("Student semester is :-",sem)
print("Student city is :-",city)
print("Student pincode is :-", pincode)
